export interface SeedDistrict {
  districtName: string;
  districtSlug: string;
  province: string;
}

export const seedDistricts: SeedDistrict[] = [
  { districtName: "Bhojpur", districtSlug: "bhojpur", province: "Koshi" },
  { districtName: "Dhankuta", districtSlug: "dhankuta", province: "Koshi" },
  { districtName: "Ilam", districtSlug: "ilam", province: "Koshi" },
  { districtName: "Jhapa", districtSlug: "jhapa", province: "Koshi" },
  { districtName: "Khotang", districtSlug: "khotang", province: "Koshi" },
  { districtName: "Morang", districtSlug: "morang", province: "Koshi" },
  { districtName: "Okhaldhunga", districtSlug: "okhaldhunga", province: "Koshi" },
  { districtName: "Panchthar", districtSlug: "panchthar", province: "Koshi" },
  { districtName: "Sankhuwasabha", districtSlug: "sankhuwasabha", province: "Koshi" },
  { districtName: "Solukhumbu", districtSlug: "solukhumbu", province: "Koshi" },
  { districtName: "Sunsari", districtSlug: "sunsari", province: "Koshi" },
  { districtName: "Taplejung", districtSlug: "taplejung", province: "Koshi" },
  { districtName: "Terhathum", districtSlug: "terhathum", province: "Koshi" },
  { districtName: "Udayapur", districtSlug: "udayapur", province: "Koshi" },
  { districtName: "Bara", districtSlug: "bara", province: "Madhesh" },
  { districtName: "Dhanusha", districtSlug: "dhanusha", province: "Madhesh" },
  { districtName: "Mahottari", districtSlug: "mahottari", province: "Madhesh" },
  { districtName: "Parsa", districtSlug: "parsa", province: "Madhesh" },
  { districtName: "Rautahat", districtSlug: "rautahat", province: "Madhesh" },
  { districtName: "Saptari", districtSlug: "saptari", province: "Madhesh" },
  { districtName: "Sarlahi", districtSlug: "sarlahi", province: "Madhesh" },
  { districtName: "Siraha", districtSlug: "siraha", province: "Madhesh" },
  { districtName: "Bhaktapur", districtSlug: "bhaktapur", province: "Bagmati" },
  { districtName: "Chitwan", districtSlug: "chitwan", province: "Bagmati" },
  { districtName: "Dhading", districtSlug: "dhading", province: "Bagmati" },
  { districtName: "Dolakha", districtSlug: "dolakha", province: "Bagmati" },
  { districtName: "Kathmandu", districtSlug: "kathmandu", province: "Bagmati" },
  { districtName: "Kavrepalanchok", districtSlug: "kavrepalanchok", province: "Bagmati" },
  { districtName: "Lalitpur", districtSlug: "lalitpur", province: "Bagmati" },
  { districtName: "Makwanpur", districtSlug: "makwanpur", province: "Bagmati" },
  { districtName: "Nuwakot", districtSlug: "nuwakot", province: "Bagmati" },
  { districtName: "Ramechhap", districtSlug: "ramechhap", province: "Bagmati" },
  { districtName: "Rasuwa", districtSlug: "rasuwa", province: "Bagmati" },
  { districtName: "Sindhuli", districtSlug: "sindhuli", province: "Bagmati" },
  { districtName: "Sindhupalchok", districtSlug: "sindhupalchok", province: "Bagmati" },
  { districtName: "Baglung", districtSlug: "baglung", province: "Gandaki" },
  { districtName: "Gorkha", districtSlug: "gorkha", province: "Gandaki" },
  { districtName: "Kaski", districtSlug: "kaski", province: "Gandaki" },
  { districtName: "Lamjung", districtSlug: "lamjung", province: "Gandaki" },
  { districtName: "Manang", districtSlug: "manang", province: "Gandaki" },
  { districtName: "Mustang", districtSlug: "mustang", province: "Gandaki" },
  { districtName: "Myagdi", districtSlug: "myagdi", province: "Gandaki" },
  { districtName: "Nawalpur", districtSlug: "nawalpur", province: "Gandaki" },
  { districtName: "Parbat", districtSlug: "parbat", province: "Gandaki" },
  { districtName: "Syangja", districtSlug: "syangja", province: "Gandaki" },
  { districtName: "Tanahun", districtSlug: "tanahun", province: "Gandaki" },
  { districtName: "Arghakhanchi", districtSlug: "arghakhanchi", province: "Lumbini" },
  { districtName: "Banke", districtSlug: "banke", province: "Lumbini" },
  { districtName: "Bardiya", districtSlug: "bardiya", province: "Lumbini" },
  { districtName: "Dang", districtSlug: "dang", province: "Lumbini" },
  { districtName: "Eastern Rukum", districtSlug: "rukum-east", province: "Lumbini" },
  { districtName: "Gulmi", districtSlug: "gulmi", province: "Lumbini" },
  { districtName: "Kapilvastu", districtSlug: "kapilvastu", province: "Lumbini" },
  { districtName: "Parasi", districtSlug: "parasi", province: "Lumbini" },
  { districtName: "Palpa", districtSlug: "palpa", province: "Lumbini" },
  { districtName: "Pyuthan", districtSlug: "pyuthan", province: "Lumbini" },
  { districtName: "Rolpa", districtSlug: "rolpa", province: "Lumbini" },
  { districtName: "Rupandehi", districtSlug: "rupandehi", province: "Lumbini" },
  { districtName: "Dailekh", districtSlug: "dailekh", province: "Karnali" },
  { districtName: "Dolpa", districtSlug: "dolpa", province: "Karnali" },
  { districtName: "Humla", districtSlug: "humla", province: "Karnali" },
  { districtName: "Jajarkot", districtSlug: "jajarkot", province: "Karnali" },
  { districtName: "Jumla", districtSlug: "jumla", province: "Karnali" },
  { districtName: "Kalikot", districtSlug: "kalikot", province: "Karnali" },
  { districtName: "Mugu", districtSlug: "mugu", province: "Karnali" },
  { districtName: "Salyan", districtSlug: "salyan", province: "Karnali" },
  { districtName: "Surkhet", districtSlug: "surkhet", province: "Karnali" },
  { districtName: "Western Rukum", districtSlug: "rukum-west", province: "Karnali" },
  { districtName: "Achham", districtSlug: "achham", province: "Sudurpashchim" },
  { districtName: "Baitadi", districtSlug: "baitadi", province: "Sudurpashchim" },
  { districtName: "Bajhang", districtSlug: "bajhang", province: "Sudurpashchim" },
  { districtName: "Bajura", districtSlug: "bajura", province: "Sudurpashchim" },
  { districtName: "Dadeldhura", districtSlug: "dadeldhura", province: "Sudurpashchim" },
  { districtName: "Darchula", districtSlug: "darchula", province: "Sudurpashchim" },
  { districtName: "Doti", districtSlug: "doti", province: "Sudurpashchim" },
  { districtName: "Kailali", districtSlug: "kailali", province: "Sudurpashchim" },
  { districtName: "Kanchanpur", districtSlug: "kanchanpur", province: "Sudurpashchim" }
];

export const provinceFromDistrictSlug = new Map(
  seedDistricts.map((district) => [district.districtSlug, district.province])
);
